---
- name: Install zoxide, fzf, and ranger
  hosts: all
  become: false  # Run tasks as the connected user, not as root
  vars:
    user_home: "{{ ansible_env.HOME }}"
    fzf_repo: "https://github.com/junegunn/fzf.git"
    fzf_dest: "{{ user_home }}/.fzf"
    fzf_bin: "{{ fzf_dest }}/bin/fzf"
  tasks:

    # ----------------------------
    # Install fzf
    # ----------------------------

    - name: Check if fzf binary exists
      ansible.builtin.stat:
        path: "{{ fzf_bin }}"
      register: fzf_stat

    - name: Check if fzf is executable
      ansible.builtin.command: "{{ fzf_bin }} --version"
      register: fzf_installed
      failed_when: false
      changed_when: false
      when: fzf_stat.stat.exists
      ignore_errors: true

    - name: Clone fzf repository
      ansible.builtin.git:
        repo: "{{ fzf_repo }}"
        dest: "{{ fzf_dest }}"
        version: 'master'
        depth: 1
      when: not fzf_stat.stat.exists or fzf_installed.failed
      register: fzf_clone
      changed_when: fzf_clone is changed

    - name: Install fzf non-interactively
      ansible.builtin.shell: |
        set -o pipefail
        bash {{ fzf_dest }}/install --all
      when: not fzf_stat.stat.exists or fzf_installed.failed
      args:
        executable: /bin/bash
      register: fzf_install
      changed_when: fzf_install.rc == 0

    # ----------------------------
    # Install ranger
    # ----------------------------

    - name: Ensure package manager cache is up to date (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts.os_family == "Debian"

    - name: Ensure package manager cache is up to date (RedHat/CentOS)
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts.os_family == "RedHat"

    - name: Install ranger via package manager
      ansible.builtin.package:
        name: ranger
        state: present

    # ----------------------------
    # Install zoxide
    # ----------------------------

    - name: Install zoxide via package manager
      ansible.builtin.package:
        name: zoxide
        state: present

    # ----------------------------
    # Install eza
    # ----------------------------

    - name: Install eza via apt
      ansible.builtin.package:
        name: eza
        state: present
      when: ansible_facts.os_family == "Debian"
      tags:
        - install
        - eza

    # ----------------------------
    # Install glow
    # ----------------------------

    - name: Ensure snapd is installed (Debian/Ubuntu)
      ansible.builtin.package:
        name: snapd
        state: present
      when: ansible_facts.os_family == "Debian"
      tags:
        - install
        - snapd

    - name: Ensure snapd is installed (RedHat/CentOS)
      ansible.builtin.package:
        name: snapd
        state: present
      when: ansible_facts.os_family == "RedHat"
      tags:
        - install
        - snapd

    - name: Enable and start snapd.socket
      ansible.builtin.systemd:
        name: snapd.socket
        enabled: true
        state: started
      when: ansible_facts.os_family in ["Debian", "RedHat"]
      tags:
        - install
        - snapd

    - name: Install glow via snap
      community.general.snap:
        name: glow
        classic: true
        state: present
      tags:
        - install
        - glow
